#port 설정
server:
  port: 9000

#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/bit701?serverTimezone=Asia/Seoul
    url: jdbc:mysql://db-g66n6-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul #내꺼
    #url: jdbc:mysql://db-g66k8-kr.vpc-pub-cdb.ntruss.com:3306/bit701?serverTimezone=Asia/Seoul #선생님꺼
    username: study
    password: bit123!@#
  servlet:
    multipart:
      max-file-size:
        20MB
#swagger 설정 (boot 2.6이후에만 추가)
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#mybatis
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml
